export const aiImagePrompts = [
    {
      app: `Midjourney`,
      imageSource: `chrisnager_grandiose_peacock_stained_glass_backlit_colorful_16k_dc90660d-c2a3-4ce1-87ed-56aded9b69d2.png`,
      prompt: `grandiose peacock, stained glass, backlit, colorful, 16k, vibrant --v 5 --ar 9:16`,
    },
    {
      app: `Midjourney`,
      imageSource: `chrisnager_sloth_kaleidoscope_vivid_colorful_7ee3154e-c50d-4c85-bc65-016a9c61a723.png`,
      prompt: `sloth kaleidoscope, vivid, colorful --v 5`,
    },
    {
      app: `Midjourney`,
      imageSource: `chrisnager_spacious_hotel_lobby_line_drawing_three-point_perspe_26a333c6-aa47-4f80-8db1-c3fb7abef025.webp`,
      prompt: `spacious hotel lobby, line drawing, three-point perspective, watercolor, black and white with yellow highlights --ar 22:17 --v 5`,
    },
    {
      app: `Midjourney`,
      imageSource: `chrisnager_Totoro_running_a_marathon_smiling_wearing_a_headband_132e4e44-fcbb-4de1-bfd2-6d0f40410707.png`,
      prompt: `Totoro running a marathon, smiling, wearing a headband, Studio Ghibli art style --ar 4:3 --niji`,
    },
    {
      app: `Midjourney`,
      imageSource: `chrisnager_a_yellow_room_with_no_windows_everything_in_the_room_7e1f9054-91fd-4860-983d-f678dbdce216.png`,
      prompt: `a yellow room with no windows, everything in the room is yellow, minimalist --ar 32:9 --v 5`,
    },
    {
      app: `Hugging Face (ControlNet v1.1)`,
      imageSource: `huggingface-controlnet-v1-1_c-logo_lineart_aerial-beach-sand-ocean-shorefront.png`,
      prompt: `[chrisnager c-logo] lineart, aerial beach, sand, ocean shorefront`,
    },
    {
      app: `Midjourney`,
      imageSource: `chrisnager_hyper-realistic_minecraft_cows_grazing_in_a_field_8k_334cd18e-6b88-4538-a8a6-d88679575eb5.png`,
      prompt: `hyper-realistic minecraft cows grazing in a field, 8k`,
    },
    {
      app: `Midjourney`,
      imageSource: `chrisnager_NYC_midtown_cab_in_the_rain_at_night_in_yellow_and_r_1f782302-344c-4ff7-a4e1-c0451ac44676.webp`,
      prompt: `NYC midtown cab in the rain, at night, in yellow and red watercolor sketch drawing, detailed, view from the street up --ar 9:16 --v 5`,
    },
    {
      app: `Midjourney`,
      imageSource: `chrisnager_Dense_repetitive_pattern_of_overlapping_cartoon_food_e8a43624-6536-4d93-9097-0eb81e0d6dd3.png`,
      prompt: `Dense repetitive pattern of overlapping cartoon food with happy faces, includes sushi, pizza, cheeseburger, hotdog, ice cream cone, and broccoli, line art, simple pastel color palette, implied depth`,
    },
    {
      app: `Adobe Firefly`,
      imageSource: `Firefly_A+curious robot without a mouth, in search of something, alone, dramatic backlighting, 4k, photorealistic._photo_56040.jpg`,
      prompt: `A curious robot without a mouth, in search of something, alone, dramatic backlighting, 4k, photorealistic. [Style: Photo]`,
    },
    {
      app: `DALL-E 2`,
      imageSource: `DALL·E 2023-04-23 13.06.38 - Shark, dark, high quality, 8-bit art.png`,
      prompt: `Shark, dark, high quality, 8-bit art`,
    },
    {
      app: `DALL-E 2`,
      imageSource: `DALL·E 2023-04-23 13.14.29 - A birthday card illustration of a lion and a fox attending a birthday party seated at a table that has a birthday cake on it with a cerulean color bac.png`,
      prompt: `A birthday card illustration of a lion and a fox attending a birthday party seated at a table that has a birthday cake on it with a cerulean color background`,
    },
    {
      app: `DALL-E 2`,
      imageSource: `DALL·E 2023-04-23 13.12.49 - Roy Lichtenstein painting of Captain Kirk fighting the Gorn.png`,
      prompt: `Roy Lichtenstein painting of Captain Kirk fighting the Gorn`,
    },
] as const

export const slugTagPairs = {
  [`accessibility`]: `Accessibility`,
  [`ai`]: `AI`,
  [`android`]: `Android`,
  [`api`]: `API`,
  [`audio`]: `Audio`,
  [`award-winning`]: `Award-winning`,
  [`basscss`]: `Basscss`,
  [`bem`]: `BEM`,
  [`branding`]: `Branding`,
  [`browser-extension`]: `Browser extension`,
  [`case-study`]: `Case study`,
  [`charting`]: `Charting`,
  [`chatbot`]: `Chatbot`,
  [`cms`]: `CMS`,
  [`color-contrast`]: `color-contrast()`,
  [`color-mix`]: `color-mix()`,
  [`color`]: `Color`,
  [`community`]: `Community`,
  [`conference`]: `Conference`,
  [`content`]: `Content`,
  [`creation`]: `Creation`,
  [`css-in-js`]: `CSS-in-JS`,
  [`css`]: `CSS`,
  [`dark-mode`]: `Dark mode`,
  [`design-hand-off`]: `Design hand-off`,
  [`design`]: `Design`,
  [`developer-experience-dx`]: `Developer experience (DX)`,
  [`documentation`]: `Documentation`,
  [`docz`]: `Docz`,
  [`engineering`]: `Engineering`,
  [`facebook-messenger-bot`]: `Facebook Messenger bot`,
  [`framework`]: `Framework`,
  [`gaming`]: `Gaming`,
  [`gatsby`]: `Gatsby`,
  [`generative-art`]: `Generative art`,
  [`giphy-api`]: `GIPHY API`,
  [`github pages`]: `GitHub Pages`,
  [`gpt-4`]: `GPT-4`,
  [`graphql`]: `GraphQL`,
  [`hack`]: `Hack`,
  [`html`]: `HTML`,
  [`idea`]: `Idea`,
  [`ios`]: `IOS`,
  [`javascript`]: `JavaScript`,
  [`jekyll`]: `Jekyll`,
  [`local storage`]: `Local storage`,
  [`logo-design`]: `Logo design`,
  [`mapbox`]: `Mapbox`,
  [`mdx`]: `MDX`,
  [`monorepo`]: `Monorepo`,
  [`music`]: `Music`,
  [`netlify`]: `Netlify`,
  [`news`]: `News`,
  [`nextjs`]: `NextJS`,
  [`openai-api`]: `OpenAI API`,
  [`openai`]: `OpenAI`,
  [`performance`]: `Performance`,
  [`positivity`]: `Positivity`,
  [`product-management`]: `Product management`,
  [`project-management`]: `Project management`,
  [`prototype`]: `Prototype`,
  [`react-native`]: `React Native`,
  [`react`]: `React`,
  [`responsive-design`]: `Responsive design`,
  [`rest`]: `REST`,
  [`sass`]: `Sass`,
  [`semantic-html`]: `Semantic HTML`,
  [`ssr`]: `SSR`,
  [`styled-system`]: `Styled-system`,
  [`svg`]: `SVG`,
  [`team-management`]: `Team management`,
  [`tooling`]: `Tooling`,
  [`twitter-api`]: `Twitter API`,
  [`typeface-design`]: `Typeface design`,
  [`typescript`]: `TypeScript`,
  [`typography`]: `Typography`,
  [`ui`]: `UI`,
  [`ux`]: `UX`,
  [`vercel integration`]: `Vercel integration`,
  [`video`]: `Video`,
  [`web-audio-api`]: `Web Audio API`,
  [`web-bluetooth-api`]: `Web Bluetooth API`,
} as const
