export const slugTagPairs = {
  [`accessibility`]: `Accessibility`,
  [`ai`]: `AI`,
  [`android`]: `Android`,
  [`api`]: `API`,
  [`audio`]: `Audio`,
  [`award-winning`]: `Award-winning`,
  [`basscss`]: `Basscss`,
  [`bem`]: `BEM`,
  [`branding`]: `Branding`,
  [`browser-extension`]: `Browser extension`,
  [`case-study`]: `Case study`,
  [`charting`]: `Charting`,
  [`cms`]: `CMS`,
  [`color-contrast`]: `color-contrast()`,
  [`color-mix`]: `color-mix()`,
  [`color`]: `Color`,
  [`community`]: `Community`,
  [`conference`]: `Conference`,
  [`content`]: `Content`,
  [`creation`]: `Creation`,
  [`css-in-js`]: `CSS-in-JS`,
  [`css`]: `CSS`,
  [`dark-mode`]: `Dark mode`,
  [`design-hand-off`]: `Design hand-off`,
  [`design`]: `Design`,
  [`developer-experience-dx`]: `Developer experience (DX)`,
  [`documentation`]: `Documentation`,
  [`docz`]: `Docz`,
  [`facebook-messenger-bot`]: `Facebook Messenger bot`,
  [`framework`]: `Framework`,
  [`gaming`]: `Gaming`,
  [`gatsby`]: `Gatsby`,
  [`generative-art`]: `Generative art`,
  [`giphy-api`]: `GIPHY API`,
  [`github pages`]: `GitHub Pages`,
  [`gpt-4`]: `GPT-4`,
  [`graphql`]: `GraphQL`,
  [`hack`]: `Hack`,
  [`html`]: `HTML`,
  [`idea`]: `Idea`,
  [`ios`]: `IOS`,
  [`javascript`]: `JavaScript`,
  [`jekyll`]: `Jekyll`,
  [`local storage`]: `Local storage`,
  [`logo-design`]: `Logo design`,
  [`mapbox`]: `Mapbox`,
  [`mdx`]: `MDX`,
  [`monorepo`]: `Monorepo`,
  [`music`]: `Music`,
  [`netlify`]: `Netlify`,
  [`news`]: `News`,
  [`nextjs`]: `NextJS`,
  [`openai-api`]: `OpenAI API`,
  [`performance`]: `Performance`,
  [`positivity`]: `Positivity`,
  [`product-management`]: `Product management`,
  [`project-management`]: `Project management`,
  [`prototype`]: `Prototype`,
  [`react-native`]: `React Native`,
  [`react`]: `React`,
  [`responsive-design`]: `Responsive design`,
  [`rest`]: `REST`,
  [`sass`]: `Sass`,
  [`semantic-html`]: `Semantic HTML`,
  [`ssr`]: `SSR`,
  [`styled-system`]: `Styled-system`,
  [`svg`]: `SVG`,
  [`team-management`]: `Team management`,
  [`tooling`]: `Tooling`,
  [`twitter-api`]: `Twitter API`,
  [`typeface-design`]: `Typeface design`,
  [`typescript`]: `TypeScript`,
  [`typography`]: `Typography`,
  [`ui`]: `UI`,
  [`ux`]: `UX`,
  [`vercel integration`]: `Vercel integration`,
  [`video`]: `Video`,
  [`web-audio-api`]: `Web Audio API`,
  [`web-bluetooth-api`]: `Web Bluetooth API`,
} as const
